# Generated by Django 5.0.2 on 2025-11-08 14:22

import app_medicinas.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id_almacen', models.AutoField(primary_key=True, serialize=False)),
                ('desc_almacen', models.CharField(default='?', max_length=400)),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'almacenes',
            },
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id_medida', models.AutoField(primary_key=True, serialize=False)),
                ('desc_medida', models.CharField(default='?', max_length=150, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'db_table': 'medidas',
            },
        ),
        migrations.CreateModel(
            name='Medicina',
            fields=[
                ('id_medicina', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_medicina', models.ImageField(blank=True, null=True, upload_to=app_medicinas.models.imagen_ruta)),
                ('desc_medicina', models.CharField(default='?', max_length=400)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50000)])),
                ('almacen_perteneciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_medicinas', to='app_medicinas.almacen')),
                ('medida_medicina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_medida', to='app_medicinas.medida')),
            ],
            options={
                'db_table': 'medicinas',
            },
        ),
    ]
