# Generated by Django 5.2.9 on 2025-12-03 14:34

import app_medicinas.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Presentacion_Medicamento',
            fields=[
                ('id_presentacion_medicamento', models.AutoField(primary_key=True, serialize=False)),
                ('desc_presentacion_medicamento', models.CharField(default='No indica', max_length=350, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
            options={
                'db_table': 'presentaciones_medicamentos',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('desc_ubicacion', models.CharField(default='No indica', max_length=400, validators=[django.core.validators.MinLengthValidator(2)])),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='Medicina',
            fields=[
                ('id_medicina', models.AutoField(primary_key=True, serialize=False)),
                ('imagen_medicina', models.ImageField(blank=True, null=True, upload_to=app_medicinas.models.imagen_ruta)),
                ('medicina', models.CharField(default='No indica', max_length=400, validators=[django.core.validators.MinLengthValidator(2)])),
                ('cantidad', models.IntegerField(default=0)),
                ('laboratorio', models.CharField(default='No indica', max_length=350, null=True, validators=[django.core.validators.MinLengthValidator(2)])),
                ('anaquel', models.CharField(default='No indica', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('descripcion', models.TextField(max_length=800)),
                ('observaciones', models.TextField(blank=True, max_length=800, null=True)),
                ('fecha_registro', models.DateField()),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_presentacion_medicamento', to='app_medicinas.presentacion_medicamento')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_ubicacion', to='app_medicinas.ubicacion')),
            ],
            options={
                'db_table': 'medicinas',
            },
        ),
    ]
