# Generated by Django 5.2.9 on 2025-12-03 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicina',
            name='creador_del_registro',
            field=models.CharField(default='No indica', max_length=350, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
