# Generated by Django 5.2.9 on 2025-12-03 14:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicinas', '0002_medicina_creador_del_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicina',
            name='anaquel',
            field=models.CharField(default='No indica', max_length=100, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
