# Generated by Django 5.2.9 on 2025-12-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicinas', '0003_alter_medicina_anaquel'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicina',
            name='historial_edicion',
            field=models.TextField(default='Sin edicion'),
        ),
    ]
