# Generated by Django 5.2.9 on 2025-12-03 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicinas', '0004_medicina_historial_edicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicina',
            name='historial_edicion',
            field=models.TextField(default='Nadie'),
        ),
    ]
