# Generated by Django 5.2.9 on 2025-12-03 18:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicinas', '0005_alter_medicina_historial_edicion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicina',
            name='cantidad',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
