# Generated by Django 5.2.9 on 2025-12-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicinas', '0006_alter_medicina_cantidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicina',
            name='autor_registro',
            field=models.CharField(blank=True, default=None, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='medicina',
            name='caducado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medicina',
            name='fecha_caducidad',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
