# Generated by Django 5.2.9 on 2025-12-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicinas', '0007_medicina_autor_registro_medicina_caducado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicina',
            name='caducado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='medicina',
            index=models.Index(fields=['caducado', 'fecha_caducidad'], name='medicinas_caducad_34f9d6_idx'),
        ),
    ]
