# Generated by Django 5.2.9 on 2025-12-15 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicinas', '0008_alter_medicina_caducado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicina',
            name='autor_registro',
        ),
    ]
