# Generated by Django 5.2.9 on 2025-12-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_medicinas', '0009_remove_medicina_autor_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicina',
            name='caducado',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
